[
    {
        "content": "<p>We are working through some problems with the DEL FASI data, which is great.  I am currently running into 412 errors.  The error returned by the Data Manager indicates: </p>\n<p>Response Body: {<br>\n  \"resourceType\": \"OperationOutcome\",<br>\n  \"id\": \"6cefb53a-d36d-447e-b25a-070799c4240b\",<br>\n  \"meta\": {<br>\n    \"versionId\": \"4ad9432c-68b7-4140-b3be-7e01273cfe3d\",<br>\n    \"lastUpdated\": \"2020-09-10T19:40:06.760+00:00\"<br>\n  },<br>\n  \"issue\": [<br>\n    {<br>\n      \"severity\": \"error\",<br>\n      \"code\": \"business-rule\",<br>\n      \"details\": {<br>\n        \"coding\": [<br>\n          {<br>\n            \"system\": \"<a href=\"http://hl7.org/fhir/dotnet-api-operation-outcome\">http://hl7.org/fhir/dotnet-api-operation-outcome</a>\",<br>\n            \"code\": \"5008\"<br>\n          }<br>\n        ],<br>\n        \"text\": \"The search criteria matches multiple existing resources. fullUrl:\"<br>\n      }<br>\n    }<br>\n  ]<br>\n}<br>\nCompleted 412 Precondition Failed in 10903ms (ActiveRecord: 0.0ms)</p>\n<p>This is new assessment data, so I'm not sure what search criteria it is referring to.  Any thoughts?</p>",
        "id": 209699443,
        "sender_full_name": "Dave Hill",
        "timestamp": 1599767097
    },
    {
        "content": "<p>What data are sent in the request body?</p>",
        "id": 209702419,
        "sender_full_name": "Vladimir Prihodko",
        "timestamp": 1599768457
    }
]