[
    {
        "content": "<p>Latest validator as of today (3.7.41) bombs out when a relative reference isn't resolvable:</p>\n<div class=\"codehilite\"><pre><span></span>Exception in thread &quot;main&quot; java.lang.Error: Not done yet - resolve Practitioner/f007 locally (2)\n    at org.hl7.fhir.r5.validation.InstanceValidator$ValidatorHostServices.resolveReference(InstanceValidator.java:232)\n</pre></div>\n\n\n<p>Is there a way to make it ignore unresovable reference? The reference is not relevant for the validity of the instance</p>",
        "id": 166984010,
        "sender_full_name": "Vadim Peretokin",
        "timestamp": 1559297089
    },
    {
        "content": "<p>can you send me an example?</p>",
        "id": 166984712,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1559297778
    },
    {
        "content": "<p>PMd</p>",
        "id": 166985867,
        "sender_full_name": "Vadim Peretokin",
        "timestamp": 1559299031
    },
    {
        "content": "<blockquote>\n<p>Latest validator as of today (3.7.41) bombs out when a relative reference isn't resolvable:</p>\n</blockquote>\n<p>Is there a resolution for this? I encounter the same problem. <br>\nSeems like all \"<a href=\"http://hl7.org\" target=\"_blank\" title=\"http://hl7.org\">hl7.org</a>\" url's that do not have a valid endpoint end in this error, both the validator and publisher demonstrate this behaviour.</p>",
        "id": 178282155,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571227823
    },
    {
        "content": "<p>Tried to validate this for example:<br>\n<a href=\"http://hl7.org/fhir/StructureDefinition/reference-targetElement\" target=\"_blank\" title=\"http://hl7.org/fhir/StructureDefinition/reference-targetElement\">http://hl7.org/fhir/StructureDefinition/reference-targetElement</a></p>",
        "id": 178282283,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571227936
    },
    {
        "content": "<p>umm I think I fixed this in the validator itself - is that what you are asking about?</p>",
        "id": 178283869,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1571229462
    },
    {
        "content": "<p>but the version suggests that this is a HAPI question?</p>",
        "id": 178283885,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1571229479
    },
    {
        "content": "<blockquote>\n<p>umm I think I fixed this in the validator itself - is that what you are asking about?</p>\n</blockquote>\n<p>Yes. It's probably not the same bug, but a similar error message.</p>",
        "id": 178292520,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571235110
    },
    {
        "content": "<p>so the java validator is ok but HAPI has a problem?</p>",
        "id": 178333705,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1571265259
    },
    {
        "content": "<blockquote>\n<p>so the java validator is ok but HAPI has a problem?</p>\n</blockquote>\n<p>I typically get error messages like this if my profile contain binding to a ValueSet defined by urn:oid:xxx. I thought that was a validator error?</p>\n<div class=\"codehilite\"><pre><span></span>Exception in thread &quot;main&quot; java.lang.Error: org.hl7.fhir.exceptions.FHIRException: not done yet: can&#39;t fetch urn:oid:2.16.578.1.12.4.1.1.7426\n    at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResource(BaseWorkerContext.java:857)\n    at org.hl7.fhir.r5.context.SimpleWorkerContext.fetchResource(SimpleWorkerContext.java:569)\n    at org.hl7.fhir.r5.validation.InstanceValidator.resolveBindingReference(InstanceValidator.java:2566)\n    at org.hl7.fhir.r5.validation.InstanceValidator.checkCodeableConcept(InstanceValidator.java:1030)\n    at org.hl7.fhir.r5.validation.InstanceValidator.checkChild(InstanceValidator.java:4086)\n    at org.hl7.fhir.r5.validation.InstanceValidator.validateElement(InstanceValidator.java:3971)\n    at org.hl7.fhir.r5.validation.InstanceValidator.checkChild(InstanceValidator.java:4099)\n    at org.hl7.fhir.r5.validation.InstanceValidator.validateElement(InstanceValidator.java:3971)\n    at org.hl7.fhir.r5.validation.InstanceValidator.start(InstanceValidator.java:2984)\n    at org.hl7.fhir.r5.validation.InstanceValidator.validateResource(InstanceValidator.java:4563)\n    at org.hl7.fhir.r5.validation.InstanceValidator.validate(InstanceValidator.java:833)\n    at org.hl7.fhir.r5.validation.InstanceValidator.validate(InstanceValidator.java:666)\n    at org.hl7.fhir.r5.validation.ValidationEngine.validate(ValidationEngine.java:1089)\n    at org.hl7.fhir.r5.validation.ValidationEngine.validate(ValidationEngine.java:1003)\n    at org.hl7.fhir.r5.validation.Validator.main(Validator.java:559)\nCaused by: org.hl7.fhir.exceptions.FHIRException: not done yet: can&#39;t fetch urn:oid:2.16.578.1.12.4.1.1.7426\n    at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResourceWithException(BaseWorkerContext.java:800)\n    at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResource(BaseWorkerContext.java:855)\n    ... 14 more\n</pre></div>",
        "id": 178655976,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571665553
    },
    {
        "content": "<p>I now have a similar error with URLs and the validator:</p>\n<div class=\"codehilite\"><pre><span></span>Terminology server: Check for supported code systems for http://hl7.org/fhir/sid/icd-10\nException in thread &quot;main&quot; java.lang.Error: Not done yet - resolve http://hl7.org/fhir/sid/icd-10\n</pre></div>\n\n\n<p>It would be great if there was an \"ignore\" flag for these kinds of errors...</p>",
        "id": 179336271,
        "sender_full_name": "Noemi Deppenwiese",
        "timestamp": 1572360720
    }
]