[
    {
        "content": "<p>Testing the open end point, this is what I get:</p>\n<p>Warning importing Patient/4342009: Conflicting identifiers 'URN:CERNER:IDENTITY-FEDERATION:REALM:0B8A0111-E8E6-4C26-A91C-5069CBC6B1CA:PRINCIPAL:ABC123' and 'URN:CERNER:IDENTITY-FEDERATION:REALM:687F29DD-69DD-4DE5-ACB1-FD8A2241EF3A:PRINCIPAL:YP2QT7JS2SA' for the same namespace 'urn:oid:2.16.840.1.113883.3.13.6'</p>\n<p>Warning importing Patient/4342009: Conflicting identifiers 'URN:CERNER:IDENTITY-FEDERATION:REALM:0B8A0111-E8E6-4C26-A91C-5069CBC6B1CA:PRINCIPAL:ABC123' and 'urn:cerner:identity-federation:realm:687f29dd-69dd-4de5-acb1-fd8a2241ef3a:principal:YP2qT7jS2sa' for the same namespace 'urn:oid:2.16.840.1.113883.3.13.6'</p>\n<p>Warning importing Practitioner/1302007: The identifier with namespace '' has no value<br>\nWarning importing Practitioner/4464007: The identifier with namespace '' has no value<br>\nWarning importing Practitioner/1600014: The identifier with namespace '' has no value<br>\nWarning importing Practitioner/1: The identifier with namespace '' has no value<br>\nWarning importing Practitioner/1590015: The identifier with namespace '' has no value<br>\nWarning importing Encounter/4027912: Unable to resolve the 'Location/35646783' Location reference<br>\nWarning importing Practitioner/4272008: The identifier with namespace '' has no value<br>\nWarning importing Practitioner/1502022: The identifier with namespace '' has no value<br>\nWarning importing Encounter/4027915: Unable to resolve the 'Location/4048303' Location reference<br>\nWarning importing Practitioner/937935: The identifier with namespace '' has no value<br>\nWarning importing Encounter/4277906: Unable to resolve the 'Location/4048302' Location reference<br>\nWarning importing Practitioner/4954007: The identifier with namespace '' has no value<br>\nWarning importing Encounter/4323909: Unable to resolve the 'Location/4048296' Location reference<br>\nWarning importing Encounter/4521906: Unable to resolve the 'Location/4048128' Location reference<br>\nWarning importing Practitioner/4646009: The identifier with namespace '' has no value<br>\nWarning importing Practitioner/4594011: The identifier with namespace '' has no value<br>\nWarning importing Encounter/4525906: Unable to resolve the 'Location/4048128' Location reference<br>\nWarning importing Encounter/4617906: Unable to resolve the 'Location/4048128' Location reference<br>\nWarning importing Practitioner/2042017: The identifier with namespace '' has no value</p>\n<p>Error importing Immunization?patient=4342009: Search Immunization failed: Type checking the data: Literal '2018-12-20T16:48:35-0600' cannot be interpreted as a instant: 'Partial is in an invalid format, should use ISO8601 YYYY-MM-DDThh:mm:ss+TZ notation'.</p>\n<p>Error importing RelatedPerson?patient=4342009: Search RelatedPerson failed: While building a POCO: Literal 'Phone' is not a valid value for enumeration 'ContactPointSystem' (at Resource.entry[0].resource[0].telecom[0].system[0])</p>",
        "id": 175621868,
        "sender_full_name": "Michele Mottini",
        "timestamp": 1568380352
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191357\">@Andrew Torres</span> ^</p>",
        "id": 175627514,
        "sender_full_name": "Michele Mottini",
        "timestamp": 1568384004
    }
]