[
    {
        "content": "<p>I recently started getting an exception from the IG Publisher:</p>\n<div class=\"codehilite\"><pre><span></span>not the right kind of structure to generate schematrons for\n</pre></div>\n\n\n<p>Attached is the log: <a href=\"/user_uploads/10155/eFD-VkYNXOazrpuXuKLXsO3v/c-cda-on-fhir-ig-publisher-build-20170711.txt\" target=\"_blank\" title=\"c-cda-on-fhir-ig-publisher-build-20170711.txt\">c-cda-on-fhir-ig-publisher-build-20170711.txt</a> </p>\n<p>This does not seem to stop the ig publisher from finishing, but I'm not sure why I am getting this exception all of the sudden. I am using the same files that I used the other day, but only updated the ig publisher to the latest version from <a href=\"http://build.fhir.org\" target=\"_blank\" title=\"http://build.fhir.org\">build.fhir.org</a>?</p>\n<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> any idea why I am suddenly getting this error?</p>",
        "id": 153896788,
        "sender_full_name": "Sean McIlvenna",
        "timestamp": 1499896464
    },
    {
        "content": "<p>no. nothing has changed down there either</p>",
        "id": 153896841,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1499957149
    },
    {
        "content": "<p>I added some context to the message.</p>",
        "id": 153896842,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1499957229
    },
    {
        "content": "<p>but we have a problem - I'm about to drop out of circulation for a couple of weeks</p>",
        "id": 153896844,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1499957247
    },
    {
        "content": "<p>If the additional context doesn't help Sean, let me know and I'll try to dig into it this weekend.</p>",
        "id": 153896870,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1499965353
    }
]