[
    {
        "content": "<p>My updated codesystem won't import into Trifolia on FHIR</p>\n<p>Error message:  Failed to call access method: org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into trm_concept (codeval, codesystem_pid, display, index_status, parent_pids, code_sequence, concept_updated, pid) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [trm_concept.IDX_CONCEPT_CS_CODE]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch</p>",
        "id": 272646861,
        "sender_full_name": "Diane",
        "timestamp": 1645425182
    },
    {
        "content": "<p>Are there any duplicate?</p>",
        "id": 272678049,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1645444390
    },
    {
        "content": "<p>Yes.  I found a duplicate.  Is that what this error means?</p>",
        "id": 272728608,
        "sender_full_name": "Diane",
        "timestamp": 1645472740
    },
    {
        "content": "<p>Not exactly, but this DataIntegrityViolationException indicates some integrity issue only with data and high chances of duplicates. Btw is it working after removing duplicates?</p>",
        "id": 272764121,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1645510644
    },
    {
        "content": "<p>Yes. It is working now. Thank you very much.</p>",
        "id": 272835236,
        "sender_full_name": "Diane",
        "timestamp": 1645549950
    },
    {
        "content": "<p>I am creating an IG and I have the following error in the Package ID field in the tab General.</p>\n<p>The ID structure is hl7.fhir.pt.HospitalDomiciliario</p>\n<p>But it gives an error, if you change pt to us, it doesn't give an error</p>\n<p>Is a step missing?</p>\n<p>output message<br>\nID hl7.fhir.pt.HospitalDomiciliario<br>\nIf this is an HL7 implementation guide, it must match the format <a href=\"http://hl7.family.realm.id\">hl7.family.realm.id</a>.<br>\n\"family\" can be \"fhir\" or \"cda\"<br>\n\"realm\" can be \"us\" or \"uv\"</p>",
        "id": 278544836,
        "sender_full_name": "Victor Costa",
        "timestamp": 1649679690
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"196223\">@Victor Costa</span> , I've asked a couple people to weigh in on this. Just waiting to hear back from them. Wanted you to know your message was received. :)</p>",
        "id": 278631639,
        "sender_full_name": "Sean McIlvenna",
        "timestamp": 1649720936
    },
    {
        "content": "<p>FYI, I know that error message you're referring to. It *should * allow you to continue, regardless of the error. It's just there as a precaution that the IG Publisher may complain about it.</p>",
        "id": 278631687,
        "sender_full_name": "Sean McIlvenna",
        "timestamp": 1649720990
    },
    {
        "content": "<p>I could be wrong, but that's why I'm waiting for others to weigh in. Stay tuned, please</p>",
        "id": 278631750,
        "sender_full_name": "Sean McIlvenna",
        "timestamp": 1649721021
    }
]