---
layout: page
title: "FHIR Chat  · InvalidDataAccessApiUsageException on hapi fhir test server · implementers"
---

{% raw %}<h2>Stream: <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/index.html">implementers</a></h2>
<h3>Topic: <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/InvalidDataAccessApiUsageException.20on.20hapi.20fhir.20test.20server.html">InvalidDataAccessApiUsageException on hapi fhir test server</a></h3>

<hr>

<base href="https://chat.fhir.org">

<head><link href="https://fhir.github.io/chat-archive/style.css" rel="stylesheet"></head>

<a name="245537988"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/InvalidDataAccessApiUsageException%20on%20hapi%20fhir%20test%20server/near/245537988" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roland Ziegler <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/InvalidDataAccessApiUsageException.20on.20hapi.20fhir.20test.20server.html#245537988">(Jul 10 2021 at 08:31)</a>:</h4>
<p>When I call <a href="http://hapi.fhir.org/baseR4/PlanDefinition?publisher=Household%20Cook&amp;status=active">http://hapi.fhir.org/baseR4/PlanDefinition?publisher=Household%20Cook&amp;status=active</a> I receive a 500 internal server error. This used to work before. Here comes the response object:</p>
<p>{<br>
  "resourceType": "OperationOutcome",<br>
  "text": {<br>
    "status": "generated",<br>
    "div": "&lt;div xmlns=\"http://www.w3.org/1999/xhtml\"&gt;&lt;h1&gt;Operation Outcome&lt;/h1&gt;&lt;table border=\"0\"&gt;&lt;tr&gt;&lt;td style=\"font-weight: bold;\"&gt;ERROR&lt;/td&gt;&lt;td&gt;[]&lt;/td&gt;&lt;td&gt;&lt;pre&gt;Failed to call access method: org.springframework.dao.InvalidDataAccessApiUsageException: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled.&lt;/pre&gt;&lt;/td&gt;\n\t\t\t&lt;/tr&gt;\n\t\t&lt;/table&gt;\n\t&lt;/div&gt;"<br>
  },<br>
  "issue": [ {<br>
    "severity": "error",<br>
    "code": "processing",<br>
    "diagnostics": "Failed to call access method: org.springframework.dao.InvalidDataAccessApiUsageException: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled."<br>
  } ]<br>
}</p>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span> : Is there anything I have to change in the way I call the endpoint or should it still work that way?</p>



<a name="246819452"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/InvalidDataAccessApiUsageException%20on%20hapi%20fhir%20test%20server/near/246819452" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roland Ziegler <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/InvalidDataAccessApiUsageException.20on.20hapi.20fhir.20test.20server.html#246819452">(Jul 22 2021 at 08:10)</a>:</h4>
<p>This seems to work again. <span aria-label="smile" class="emoji emoji-1f642" role="img" title="smile">:smile:</span></p>


{% endraw %}
<hr><p>Last updated: Apr 12 2022 at 19:14 UTC</p>
