[
    {
        "content": "<p>I have Docker Desktop installed in a Windows VM.  I cloned the inferno project using git clone <a href=\"https://github.com/onc-healthit/inferno\">https://github.com/onc-healthit/inferno</a>.  In the inferno directory, I am tried to run:<br>\ndocker-compose up and got the following error:<br>\n  File \"docker-compose\", line 3, in &lt;module&gt;<br>\n  File \"compose\\cli\\main.py\", line 67, in main<br>\n  File \"compose\\cli\\main.py\", line 123, in perform_command<br>\n  File \"compose\\cli\\command.py\", line 69, in project_from_options<br>\n  File \"compose\\cli\\command.py\", line 132, in get_project<br>\n  File \"compose\\cli\\docker_client.py\", line 43, in get_client<br>\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client<br>\n  File \"site-packages\\docker\\api\\client.py\", line 188, in __init__<br>\n  File \"site-packages\\docker\\api\\client.py\", line 213, in _retrieve_server_version<br>\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')<br>\n[1988] Failed to execute script docker-compose</p>\n<p>I then tried to do a build using docker-compose up --build and get the same error:<br>\nTraceback (most recent call last):<br>\n  File \"docker-compose\", line 3, in &lt;module&gt;<br>\n  File \"compose\\cli\\main.py\", line 67, in main<br>\n  File \"compose\\cli\\main.py\", line 123, in perform_command<br>\n  File \"compose\\cli\\command.py\", line 69, in project_from_options<br>\n  File \"compose\\cli\\command.py\", line 132, in get_project<br>\n  File \"compose\\cli\\docker_client.py\", line 43, in get_client<br>\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client<br>\n  File \"site-packages\\docker\\api\\client.py\", line 188, in __init__<br>\n  File \"site-packages\\docker\\api\\client.py\", line 213, in _retrieve_server_version<br>\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')<br>\n[11720] Failed to execute script docker-compose</p>\n<p>Any suggestions on how to resolve this error are greatly appreciated</p>",
        "id": 211499277,
        "sender_full_name": "Padma Nippani",
        "timestamp": 1601303174
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"347035\">@Padma Nippani</span> -- I haven't seen that issue before, but it looks like Docker isn't configured properly somehow?  What version of Docker Desktop (and Docker Compose) are you running?  Are you able to run the Docker \"hello-world\" example successfully (<code>docker run hello-world</code>)?</p>",
        "id": 211509055,
        "sender_full_name": "Robert Scanlon",
        "timestamp": 1601307397
    },
    {
        "content": "<p>Hi Robert, </p>\n<p>Thank you very much for your quick response.  I am trying docker version and docker run hello-world and get an error.  It does appear that my docker desktop is not installed correctly.  Trying to correct that now and will update here soon</p>",
        "id": 211514209,
        "sender_full_name": "Padma Nippani",
        "timestamp": 1601309854
    },
    {
        "content": "<p>I realized that I was seeing errors with docker desktop installation on my windows VM.  I installed it on my mac and running docker-compose up now displays the following error building ruby server:<br>\nRetrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from <a href=\"https://rubygems.org/\">https://rubygems.org/</a></p>\n<p>Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from <a href=\"https://rubygems.org/\">https://rubygems.org/</a><br>\nRetrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from <a href=\"https://rubygems.org/\">https://rubygems.org/</a></p>\n<p>Could not fetch specs from <a href=\"https://rubygems.org/\">https://rubygems.org/</a><br>\nERROR: Service 'ruby_server' failed to build : The command '/bin/sh -c bundle install' returned a non-zero code: 17</p>",
        "id": 211534203,
        "sender_full_name": "Padma Nippani",
        "timestamp": 1601319330
    },
    {
        "content": "<p>Inferno is a ruby app, which downloads dependencies from <a href=\"https://rubygems.org\">https://rubygems.org</a> when you first run it.  Would there by any reason why that might be blocked on your network?</p>",
        "id": 211537939,
        "sender_full_name": "Robert Scanlon",
        "timestamp": 1601321087
    },
    {
        "content": "<p>Thanks Robert.  I can access <a href=\"https://rubygems.org\">https://rubygems.org</a> from my browser so the site is not blocked on our network.</p>",
        "id": 211539696,
        "sender_full_name": "Padma Nippani",
        "timestamp": 1601321970
    },
    {
        "content": "<p>I looked at docker configuration and had to add file sharing to the directory where I was installing.  Now I get the following error:<br>\nFetching gem metadata from <a href=\"https://rubygems.org/\">https://rubygems.org/</a>.........<br>\nFetching rake 12.3.3<br>\nInstalling rake 12.3.3<br>\nFetching concurrent-ruby 1.1.6<br>\nInstalling concurrent-ruby 1.1.6<br>\nFetching i18n 1.8.5<br>\nInstalling i18n 1.8.5<br>\nFetching minitest 5.14.1</p>\n<p>Retrying download gem from <a href=\"https://rubygems.org/\">https://rubygems.org/</a> due to error (2/4): Gem::RemoteFetcher::UnknownHostError no such name (<a href=\"https://rubygems.org/gems/minitest-5.14.1.gem\">https://rubygems.org/gems/minitest-5.14.1.gem</a>)</p>\n<p>Retrying download gem from <a href=\"https://rubygems.org/\">https://rubygems.org/</a> due to error (3/4): Gem::RemoteFetcher::UnknownHostError no such name (<a href=\"https://rubygems.org/gems/minitest-5.14.1.gem\">https://rubygems.org/gems/minitest-5.14.1.gem</a>)</p>\n<p>Retrying download gem from <a href=\"https://rubygems.org/\">https://rubygems.org/</a> due to error (4/4): Gem::RemoteFetcher::UnknownHostError no such name (<a href=\"https://rubygems.org/gems/minitest-5.14.1.gem\">https://rubygems.org/gems/minitest-5.14.1.gem</a>)</p>\n<p>Gem::RemoteFetcher::UnknownHostError: no such name<br>\n(<a href=\"https://rubygems.org/gems/minitest-5.14.1.gem\">https://rubygems.org/gems/minitest-5.14.1.gem</a>)<br>\nAn error occurred while installing minitest (5.14.1), and Bundler cannot<br>\ncontinue.<br>\nMake sure that <code>gem install minitest -v '5.14.1' --source\n'https://rubygems.org/'</code> succeeds before bundling.</p>\n<p>In Gemfile:<br>\n  fhir_client was resolved to 4.0.3, which depends on<br>\n    activesupport was resolved to 5.2.4.3, which depends on<br>\n      minitest<br>\nERROR: Service 'ruby_server' failed to build : The command '/bin/sh -c bundle install' returned a non-zero code: 5</p>",
        "id": 211540105,
        "sender_full_name": "Padma Nippani",
        "timestamp": 1601322177
    },
    {
        "content": "<p>That's really strange, I don't understand why it was able to fetch the first 3 libraries but then fail with a host lookup error on the forth, when they are all coming from the same spot.  Does it always fail in that exact spot now?</p>",
        "id": 211543979,
        "sender_full_name": "Robert Scanlon",
        "timestamp": 1601323900
    },
    {
        "content": "<p>I was able to sudo gem install to install minitest and continue.  But now, I keep getting an error for a different gem.  Sometimes, is the the same one that I have already installed.  I am unable to get out of the cycle to fetching and installing gems.  I am running on a mac and checked that file sharing is set up for the directories.</p>",
        "id": 211549137,
        "sender_full_name": "Padma Nippani",
        "timestamp": 1601326513
    }
]