[
    {
        "content": "<p>Getting the following error POSTing a transaction to the public hapi 4 server - was working a couple of minutes ago...<br>\n{<br>\n  \"resourceType\": \"OperationOutcome\",<br>\n  \"text\": {<br>\n    \"status\": \"generated\",<br>\n    \"div\": \"&lt;div xmlns=\\\"http://www.w3.org/1999/xhtml\\\"&gt;&lt;h1&gt;Operation Outcome&lt;/h1&gt;&lt;table border=\\\"0\\\"&gt;&lt;tr&gt;&lt;td style=\\\"font-weight: bold;\\\"&gt;ERROR&lt;/td&gt;&lt;td&gt;[]&lt;/td&gt;&lt;td&gt;&lt;pre&gt;Failed to call access method: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection&lt;/pre&gt;&lt;/td&gt;\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t&lt;/tr&gt;\\n\\t\\t&lt;/table&gt;\\n\\t&lt;/div&gt;\"<br>\n  },<br>\n  \"issue\": [<br>\n    {<br>\n      \"severity\": \"error\",<br>\n      \"code\": \"processing\",<br>\n      \"diagnostics\": \"Failed to call access method: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection\"<br>\n    }<br>\n  ]<br>\n}</p>",
        "id": 175942870,
        "sender_full_name": "David Hay",
        "timestamp": 1568750265
    },
    {
        "content": "<p>eep, looks like the hard drive is full n that server...</p>",
        "id": 175944272,
        "sender_full_name": "James Agnew",
        "timestamp": 1568751246
    },
    {
        "content": "<p>Sigh...</p>\n<p>I enabled Bulk Data export this weekend, and enough people generated bulk exports that it trashed the database. Ugggggh I hate recovering from this kind of thing :)</p>",
        "id": 175946962,
        "sender_full_name": "James Agnew",
        "timestamp": 1568752947
    }
]